### PR TITLE
added 'data-' attribute to regexList

### PR DESCRIPTION
**Pull request by cor03rock**

### CODE REVIEW

**Comment by stramel** [comment]
It may be better to strip `data-` off of any attribute for the regex instead of duplicating the code for each type or perhaps extending it to use an array of `attrNames` instead?

**Comment by ramonvictor** [comment]
@stramel you are completely right. We need to solve this problem in the core of the module, otherwise we'd need to duplicate all new regex rules. I'll try to fix this in a more appropriate way. Sorry for taking so long to reply.

**Comment by cor03rock** [comment]
I'll wait for the fix for this @ramonvictor , we really need this tool in our team.

**Comment by ramonvictor** [comment]
Just a heads up: fix has been published on version [0.1.18](https://www.npmjs.com/package/gulp-protractor-qa). This is the commit that fixes the bug: https://github.com/ramonvictor/gulp-protractor-qa/commit/ff03a15ed35067e92570fcac880e405ba6cde83c#diff-168726dbe96b3ce427e7fedce31bb0bcR128.
Sorry for my delay, one more time, and thanks for spotting the issue.

**Pull request closed without merging**
